resolver: lts-12.4

packages:
- .

extra-deps: 
- extensible-effects-3.0.0.0

# nix:
#   enable: true
#   pure: true
#   path:
#     - nixpkgs=/home/nat/.nix-defexpr/channels/unstable
#   packages:
#     - zlib
